# Generated by Django 5.0 on 2023-12-26 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fguess', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
            ],
        ),
    ]
